### ISSUE TITLE
How to solve this mistake

### ISSUE THREAD

**Issue by wiki-qi** [GpunionProject/Gpuniontoken#1]
OS:Ubuntu16.04 

/usr/bin/ld: crypto/libgpunion_crypto.a(crypto_libgpunion_crypto_a-blake.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
crypto/libgpunion_crypto.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:3787: recipe for target 'gpunion-tx' failed
make[2]: *** [gpunion-tx] Error 1
make[2]: *** Waiting for unfinished jobs....
/usr/bin/ld: crypto/libgpunion_crypto.a(crypto_libgpunion_crypto_a-blake.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
crypto/libgpunion_crypto.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:3791: recipe for target 'gpuniond' failed
make[2]: *** [gpuniond] Error 1

**Comment by GpunionProject** [comment]
Please retry with

CFLAGS="-fPIC" ./configure --without-gui
